# Plan of Attack

In [2]:
import math

In [3]:
math.sqrt(25)

5.0

In [4]:
math.pi

3.141592653589793

In [5]:
import math as mt

In [6]:
mt.sqrt(25)

5.0

In [8]:
import numpy as np

In [9]:
import stats from scipy

SyntaxError: invalid syntax (<ipython-input-9-8eecefd8e6be>, line 1)

In [10]:
from scipy import stats as st

In [12]:
from numpy import random

In [13]:
# uniform random numbers in [0,1]
dataOne = random.rand(5,5)

In [14]:
print(dataOne)

[[0.46962911 0.53453764 0.38768652 0.285498   0.12679068]
 [0.78138512 0.33006505 0.13864307 0.71423452 0.01868681]
 [0.45252952 0.72904016 0.40830375 0.92697696 0.8109305 ]
 [0.79185501 0.35244402 0.50346428 0.80598739 0.69483299]
 [0.36740111 0.84867128 0.41487007 0.05487466 0.53783991]]


In [15]:
np.mean(dataOne)

0.4994871254957938

In [25]:
#math functions
mt.log10(dataOne)

#error : You are getting the error "only length-1 
#arrays can be converted to Python scalars" is because 
#when the function expects a single value instead of that you have passed an array. 

TypeError: only size-1 arrays can be converted to Python scalars

In [19]:
#stats functions
st.describe(dataOne)

DescribeResult(nobs=5, minmax=(array([0.36740111, 0.33006505, 0.13864307, 0.05487466, 0.01868681]), array([0.79185501, 0.84867128, 0.50346428, 0.92697696, 0.8109305 ])), mean=array([0.57255997, 0.55895163, 0.37059354, 0.5575143 , 0.43781618]), variance=array([0.03969762, 0.05212452, 0.01878257, 0.13736056, 0.12192074]), skewness=array([ 0.28968351,  0.19792013, -1.08452473, -0.42547737, -0.22188239]), kurtosis=array([-1.74957816, -1.56848008, -0.15461794, -1.47040046, -1.65322217]))

In [20]:
st.variation(dataOne)

array([0.31124777, 0.36533544, 0.33076892, 0.59459329, 0.71333246])

In [21]:
st.find_repeats(dataOne)

RepeatedResults(values=array([], dtype=float64), counts=array([], dtype=int64))

In [22]:
st.skew(dataOne)

array([ 0.28968351,  0.19792013, -1.08452473, -0.42547737, -0.22188239])

In [23]:
st.mode(dataOne)

ModeResult(mode=array([[0.36740111, 0.33006505, 0.13864307, 0.05487466, 0.01868681]]), count=array([[1, 1, 1, 1, 1]]))

Functions

In [26]:
functionName()

NameError: name 'functionName' is not defined

In [27]:
print('I Love data Science')

I Love data Science


In [28]:
#Variables
variableName = 25

In [29]:
variableName1 = 'I Love data Science'

In [30]:
print(variableName1)

I Love data Science


DataTypes

In [31]:
variableName = 25

In [32]:
type(variableName)

int

In [33]:
variableName = 25.0

In [34]:
type(variableName)

float

In [35]:
varOne = 25

In [36]:
varTwo = 25.0

In [37]:
varThree = varOne + varTwo

In [38]:
print(varThree)

50.0


In [39]:
type(varThree)

float

In [40]:
varOne = 25

In [41]:
varTwo = 'Hello'

In [42]:
varThree = varOne + varTwo
#error: different data types cannot being sum

TypeError: unsupported operand type(s) for +: 'int' and 'str'

In [43]:
print(varThree)

50.0


Lists and Dictionaries

In [44]:
listName = [ ]

In [45]:
listOne = [1,2,3,4]

In [46]:
print(listOne[1:3])

[2, 3]


In [47]:
tel = {'jack': 4098, 'sape': 4139}

In [48]:
tel['jack']

4098

In [49]:
age = {'naza': 25, 'mari': 24, 'glori': 3, 'naza u': 24, 'elena': 24}

In [50]:
mt.log10(age['naza'])

1.3979400086720377

In [52]:
mt.expm1(age['glori'])

19.085536923187668

In [53]:
mt.tan(age['mari'])

-2.1348966977217008

# Tutorial 

In [56]:
the_world_is_flat = True
if the_world_is_flat:
     print("Be careful not to fall off!")

Be careful not to fall off!


In [58]:
# this is the first comment
spam = 1  # and this is the second comment
          # ... and now a third!
text = "# This is not a comment because it's inside quotes."
print(text)

# This is not a comment because it's inside quotes.


NUMBERS

In [59]:
2+2

4

In [60]:
50-5*6

20

In [61]:
(50-5*6)/4

5.0

In [62]:
8/5 # division always returns a floating point number

1.6

In [63]:
17 / 3  # classic division returns a float

5.666666666666667

In [64]:
17 // 3  # floor division discards the fractional part

5

In [65]:
17 % 3  # the % operator returns the remainder of the division

2

In [66]:
5 * 3 + 2  # result * divisor + remainder

17

In [67]:
5 ** 2  # 5 squared

25

In [68]:
2 ** 7  # 2 to the poqwer of 7

128

In [69]:
width = 20
height = 5 * 9
width * height

900

In [71]:
n  # try to access an undefined variable

NameError: name 'n' is not defined

In [72]:
4 * 3.75 - 1

14.0

In [73]:
tax = 12.5 / 100
price = 100.50
price * tax



12.5625

In [74]:
price + _

113.0625

In [75]:
round(_, 2)

113.06

Strings

In [78]:
'spam eggs'  # single quotes

'spam eggs'

In [77]:
'doesn\'t'  # use \' to escape the single quote...

"doesn't"

In [79]:
"doesn't"  # ...or use double quotes instead

"doesn't"

In [80]:
'"Yes," they said.'

'"Yes," they said.'

In [81]:
'"Yes," they said.'

'"Yes," they said.'

In [82]:
'"Isn\'t," they said.'

'"Isn\'t," they said.'

In [83]:
'"Isn\'t," they said.'

'"Isn\'t," they said.'

In [84]:
print('"Isn\'t," they said.')

"Isn't," they said.


In [86]:
s = 'First line.\nSecond line.'  # \n means newline
print(s)

First line.
Second line.


In [87]:
print('C:\some\name')  # here \n means newline!

C:\some
ame


In [88]:
print(r'C:\some\name')  # note the r before the quote

C:\some\name


In [89]:
print("""\
Usage: thingy [OPTIONS]
     -h                        Display this usage message
     -H hostname               Hostname to connect to
""")

Usage: thingy [OPTIONS]
     -h                        Display this usage message
     -H hostname               Hostname to connect to



In [91]:
# 3 times 'un', followed by 'ium'
3 * 'un' + 'ium'

'unununium'

In [92]:
'Py' 'thon'

'Python'

In [93]:
text = ('Put several strings within parentheses '
...         'to have them joined together.')

In [94]:
print(text)

Put several strings within parentheses to have them joined together.


In [95]:
text

'Put several strings within parentheses to have them joined together.'

In [97]:
prefix = 'Py'
prefix 'thon'  # can't concatenate a variable and a string literal

SyntaxError: invalid syntax (<ipython-input-97-20527b549823>, line 2)

In [98]:
prefix + 'thon'

'Python'

In [99]:
word = 'Python'
word[0]  # character in position 0

'P'

In [100]:
word[5]  # character in position 5

'n'

In [101]:
word[-1]  # last character

'n'

In [102]:
word[-2]  # second-last character

'o'

In [103]:
word[-6]

'P'

In [104]:
word[0:2]  # characters from position 0 (included) to 2 (excluded)

'Py'

In [105]:
word[2:5]  # characters from position 2 (included) to 5 (excluded)

'tho'

In [106]:
word[:2] + word[2:]

'Python'

In [107]:
word[:4] + word[4:]

'Python'

In [108]:
word[:2]   # character from the beginning to position 2 (excluded)

'Py'

In [109]:
word[4:]   # characters from position 4 (included) to the end

'on'

In [110]:
word[-2:]  # characters from the second-last (included) to the end

'on'

In [111]:
word[42]  # the word only has 6 characters

IndexError: string index out of range

In [112]:
word[4:42]

'on'

In [113]:
word[42:]

''

In [114]:
word[0] = 'J'

TypeError: 'str' object does not support item assignment

In [115]:
'J' + word[1:]

'Jython'

In [116]:
word[:2] + 'py'

'Pypy'

In [117]:
s = 'supercalifragilisticexpialidocious'

In [118]:
len(s)

34

Lists

In [119]:
squares = [1, 4, 9, 16, 25]

In [120]:
squares

[1, 4, 9, 16, 25]

In [121]:
squares[0]  # indexing returns the item

1

In [122]:
squares[-1]

25

In [123]:
squares[-3:]  # slicing returns a new list

[9, 16, 25]

In [124]:
squares[:]

[1, 4, 9, 16, 25]

In [125]:
squares + [36, 49, 64, 81, 100]

[1, 4, 9, 16, 25, 36, 49, 64, 81, 100]

In [127]:
cubes = [1, 8, 27, 65, 125]  # something's wrong here

In [128]:
4 ** 3  # the cube of 4 is 64, not 65!

64

In [129]:
cubes[3] = 64  # replace the wrong value

In [130]:
cubes

[1, 8, 27, 64, 125]

In [131]:
cubes.append(216)  # add the cube of 6

In [132]:
cubes.append(7 ** 3)  # and the cube of 7

In [133]:
cubes

[1, 8, 27, 64, 125, 216, 343]

In [134]:
letters = ['a', 'b', 'c', 'd', 'e', 'f', 'g']
letters

['a', 'b', 'c', 'd', 'e', 'f', 'g']

In [135]:
# replace some values
letters[2:5] = ['C', 'D', 'E']
letters

['a', 'b', 'C', 'D', 'E', 'f', 'g']

In [136]:
# now remove them
letters[2:5] = []

letters

['a', 'b', 'f', 'g']

In [137]:
# clear the list by replacing all the elements with an empty list
letters[:] = []
letters
[]

[]

In [138]:
letters = ['a', 'b', 'c', 'd']
len(letters)
4

4

In [140]:
a = ['a', 'b', 'c']
n = [1, 2, 3]
x = [a, n]
x


[['a', 'b', 'c'], [1, 2, 3]]

In [141]:
x[0]

['a', 'b', 'c']

In [142]:
x[0][1]

'b'

First Steps Towards Programming

In [146]:
# the sum of two elements defines the next
a, b = 0, 1
while a < 10:
    print(a)
    a, b = b, a+b

    

0
1
1
2
3
5
8


In [145]:
i = 256*256
print('The value of i is', i)

The value of i is 65536


In [147]:
a, b = 0, 1
while a < 1000:
    print(a, end=',')
    a, b = b, a+b
    

0,1,1,2,3,5,8,13,21,34,55,89,144,233,377,610,987,

More Control Flow Tools
if Statements

In [149]:
x=int(input("Please enter an integer: "))
if x < 0:
    x=0
    print('Negative changed to zero')
elif x ==0:
    print('zero')
elif x ==1:
    print('single')
else:
    print('More')
    
    

Please enter an integer: -2
Negative changed to zero


For statements

In [150]:
#Measure some strings:
words = ['cat', 'window', 'defenestrate']
for w in words:
    print(w, len(w))

cat 3
window 6
defenestrate 12


In [152]:
#strategy: iterate over a copy
for user, status in users.copy().items():
    if status == 'inactive':
        del users[user]
        
#strategy: create a new collection
active_users = {}
for user, status in users.items():
    if status == 'active':
        active_users[user] = status

NameError: name 'users' is not defined

The range() function

In [154]:
for i in range(5):
    print(i)

0
1
2
3
4


In [156]:
for i in range(5,10):
    print(i)

5
6
7
8
9


In [157]:
for i in range(0,10,3):
    print(i)

0
3
6
9


In [158]:
for i in range(-10, -100, -30):
    print(i)

-10
-40
-70


In [159]:
a=['Mary', 'had', 'a', 'little', 'lamb']
for i in range(len(a)):
    print(i, a[i])

0 Mary
1 had
2 a
3 little
4 lamb


In [160]:
print(range(10))

range(0, 10)


# Final Remarks

In [161]:
sum(range(4)) #0+1+2+3

6

In [162]:
list(range(4))

[0, 1, 2, 3]

break and continue Statements, and else Clauses on Loops¶

In [163]:
for n in range(2,10):
    for x in range(2,n):
        if n % x == 0:
            print(n, 'equals', x, '*', n//x)
    else:
        #loop fell through without finding a factor
        print(n, 'is a primer number')

2 is a primer number
3 is a primer number
4 equals 2 * 2
4 is a primer number
5 is a primer number
6 equals 2 * 3
6 equals 3 * 2
6 is a primer number
7 is a primer number
8 equals 2 * 4
8 equals 4 * 2
8 is a primer number
9 equals 3 * 3
9 is a primer number


In [164]:
for num in range(2,10):
    if num % 2 ==0:
        print('Found an even number', num)
        continue
    print('Found a number', num)
    

Found an even number 2
Found a number 3
Found an even number 4
Found a number 5
Found an even number 6
Found a number 7
Found an even number 8
Found a number 9


pass statetemens

In [166]:
while True:
    pass #busy-wait for keyboard interrupt (ctrl+c)

KeyboardInterrupt: 

In [167]:
class MyEmptyClass:
    pass

In [168]:
def initlog(*args):
    pass 

Defining Functions

In [169]:
def fib(n): #write Fibonacci series up to n
    """Print a Fibonacci series up to n."""
    a,b = 0,1
    while a < n:
        print(a, end=' ')
        a, b = b, a+b
    print()

In [170]:
fib(2000)

0 1 1 2 3 5 8 13 21 34 55 89 144 233 377 610 987 1597 


In [171]:
fib

<function __main__.fib(n)>

In [172]:
f = fib
f(100)

0 1 1 2 3 5 8 13 21 34 55 89 


In [173]:
fib(0)
print(fib(0))



None


In [175]:
def fib2(n):
    """Return a list containing the Fibonacci series up to n."""
    result = []
    a,b = 0,1
    while a < n:
        result.append(a)
        a, b = b, a + b
    return result

f100 = fib2(100)
f100

[0, 1, 1, 2, 3, 5, 8, 13, 21, 34, 55, 89]

In [180]:
def ask_ok(prompt, retries=4, reminder='Please try again!'):
    while True:
        ok = input(prompt)
        if ok in ('y', 'ye', 'yes'):
            return True
        if ok in ('n', 'no', 'nop', 'nope'):
            return False
        retries = retries - 1
        if retries < 0:
            raise ValueError('invalid user response')
        print(reminder)

In [181]:
i= 5

def f(arg=i):
    print(arg)

i=6
f()

5


In [182]:
def f(a, L=[]):
    L.append(a)
    return L

print(f(1))
print(f(2))
print(f(3))

[1]
[1, 2]
[1, 2, 3]


In [183]:
def f(a, L=None):
    if L is None:
        L=[]
    L.append(a)
    return L

Keyword Arguments

In [185]:
def parrot(voltage, state='a stiff', action='voom', type='Norwegian Blue'):
    print("-- This parrot wouldn't", action, end=' ')
    print("if you put", voltage, "volts through it.")
    print("-- Lovely plumage, the", type)
    print("-- It's", state, "!")

In [186]:
parrot(1000)                                          # 1 positional argument
parrot(voltage=1000)                                  # 1 keyword argument
parrot(voltage=1000000, action='VOOOOOM')             # 2 keyword arguments
parrot(action='VOOOOOM', voltage=1000000)             # 2 keyword arguments
parrot('a million', 'bereft of life', 'jump')         # 3 positional arguments
parrot('a thousand', state='pushing up the daisies')  # 1 positional, 1 keyword

-- This parrot wouldn't voom if you put 1000 volts through it.
-- Lovely plumage, the Norwegian Blue
-- It's a stiff !
-- This parrot wouldn't voom if you put 1000 volts through it.
-- Lovely plumage, the Norwegian Blue
-- It's a stiff !
-- This parrot wouldn't VOOOOOM if you put 1000000 volts through it.
-- Lovely plumage, the Norwegian Blue
-- It's a stiff !
-- This parrot wouldn't VOOOOOM if you put 1000000 volts through it.
-- Lovely plumage, the Norwegian Blue
-- It's a stiff !
-- This parrot wouldn't jump if you put a million volts through it.
-- Lovely plumage, the Norwegian Blue
-- It's bereft of life !
-- This parrot wouldn't voom if you put a thousand volts through it.
-- Lovely plumage, the Norwegian Blue
-- It's pushing up the daisies !


In [188]:
parrot()                     # required argument missing
parrot(voltage=5.0,'dead')  # non-keyword argument after a keyword argument
parrot(110, voltage=220)     # duplicate value for the same argument
parrot(actor='John Cleese')  # unknown keyword argument

SyntaxError: positional argument follows keyword argument (<ipython-input-188-f8b189e393f0>, line 2)

In [189]:
def function(a):
    pass

function(0, a =0)

TypeError: function() got multiple values for argument 'a'

In [190]:
def cheeseshop(kind, *arguments, **keywords):
    print("-- Do you have any", kind, "?")
    print("-- I'm sorry, we're all out of", kind)
    for arg in arguments:
        print(arg)
    print("-" * 40)
    for kw in keywords:
        print(kw, ":", keywords[kw])

In [191]:
cheeseshop("Limburger", "It's very runny, sir.",
           "It's really very, VERY runny, sir.",
           shopkeeper="Michael Palin",
           client="John Cleese",
           sketch="Cheese Shop Sketch")

-- Do you have any Limburger ?
-- I'm sorry, we're all out of Limburger
It's very runny, sir.
It's really very, VERY runny, sir.
----------------------------------------
shopkeeper : Michael Palin
client : John Cleese
sketch : Cheese Shop Sketch


Function examples

In [192]:
def standard_arg(arg):
    print(arg)

In [199]:
def pos_only_arg(arg,/):
    print(arg)

SyntaxError: invalid syntax (<ipython-input-199-6bb076145948>, line 1)

In [194]:
def kwd_only_arg(*, arg):
    print(arg)

In [195]:
def combined_example(pos_only, /, standard, *, kwd_only):
    print(pos_only, standard, kwd_only)

SyntaxError: invalid syntax (<ipython-input-195-e71a7fd473ab>, line 1)

In [196]:
standard_arg(2)

2


In [197]:
standard_arg(arg=2)

2


In [198]:
pos_only_arg(1)

NameError: name 'pos_only_arg' is not defined

In [200]:
kwd_only_arg(3)

TypeError: kwd_only_arg() takes 0 positional arguments but 1 was given

In [201]:
combined_example(1,2,3)

NameError: name 'combined_example' is not defined

In [202]:
combined_example(1,2, kwd_only=3)

NameError: name 'combined_example' is not defined

In [203]:
def foo(name, **kwds):
    return 'name' in kwds

In [204]:
foo(1, **{'name':2})

TypeError: foo() got multiple values for argument 'name'

In [209]:
def foo(name, "/", **kwds):
    return 'name' in kwds

SyntaxError: invalid syntax (<ipython-input-209-544fd919e9e8>, line 1)

In [206]:
def write_multiple_items(file, separator, *args):
    file.write(separator.join(args))

In [207]:
def concat(*args, sep="/"):
    return sep.join(args)

In [208]:
concat("earth", "mars", "venus")

'earth/mars/venus'

In [210]:
concat("earth", "mars", "venus", sep=".")

'earth.mars.venus'

In [211]:
list(range(3,6))

[3, 4, 5]

In [212]:
args = [3,6]
list(range(*args))

[3, 4, 5]

In [213]:
def parrot(voltage, state='a stiff', action='voom'):
     print("-- This parrot wouldn't", action, end=' ')
     print("if you put", voltage, "volts through it.", end=' ')
     print("E's", state, "!")

d = {"voltage": "four million", "state": "bleedin' demised", "action": "VOOM"}
parrot(**d)
#This parrot wouldn't VOOM if you put four million volts through it. E's bleedin' demised !

-- This parrot wouldn't VOOM if you put four million volts through it. E's bleedin' demised !


Lamba Expressions

In [215]:
def make_incrementor (n):
    return lambda x: x + n

f = make_incrementor(42)
f(0)

42

In [216]:
f(1)

43

In [217]:
f(3)

45

In [219]:
pairs = [(1, 'one'), (2, 'two'), (3, 'three'), (4, 'four')]
pairs.sort(key=lambda pair: pair[1])
pairs

[(4, 'four'), (1, 'one'), (3, 'three'), (2, 'two')]

Document Strings

In [220]:
def my_function():
    """Do nothing, but document it.
    
    No, really, it doesn't do anything
    """
    pass

print(my_function.__doc__)

Do nothing, but document it.
    
    No, really, it doesn't do anything
    


Function Annotations

In [221]:
def f(ham: str, eggs: str= 'eggs') -> str:
    print("Annotations:", f.__annotations__)
    print("Arguments:", ham, eggs)
    return ham + ' and ' + eggs

f('spam')

Annotations: {'ham': <class 'str'>, 'eggs': <class 'str'>, 'return': <class 'str'>}
Arguments: spam eggs


'spam and eggs'

Data Structures

In [222]:
fruits = ['orange', 'apple', 'pear', 'banana', 'kiwi', 'apple', 'banana']
fruits.count('apple')

2

In [223]:
fruits.count('tangerine')

0

In [224]:
fruits.index('banana')

3

In [225]:
fruits.index('banana', 4) # Find next banana starting a position 4

6

In [226]:
fruits.reverse()

In [227]:
fruits

['banana', 'apple', 'kiwi', 'banana', 'pear', 'apple', 'orange']

In [228]:
fruits.append('grape')

In [229]:
fruits

['banana', 'apple', 'kiwi', 'banana', 'pear', 'apple', 'orange', 'grape']

In [230]:
fruits.sort()

In [231]:
fruits

['apple', 'apple', 'banana', 'banana', 'grape', 'kiwi', 'orange', 'pear']

In [232]:
fruits.pop()

'pear'

Using Lists as Stacks

In [233]:
stack = [3,4,5]
stack.append(6)
stack.append(7)
stack

[3, 4, 5, 6, 7]

In [234]:
stack.pop()

7

In [235]:
stack

[3, 4, 5, 6]

In [236]:
stack.pop()

6

In [237]:
stack.pop()

5

In [238]:
stack

[3, 4]

Using Lists as Queues

In [239]:
from collections import deque
queue = deque(["Eric", "John", "Michael"])
queue.append("Terry")           # Terry arrives
queue.append("Graham")          # Graham arrives
queue.popleft()                 # The first to arrive now leaves


'Eric'

In [240]:
queue.popleft()                 # The second to arrive now leaves

'John'

In [241]:
queue                           # Remaining queue in order of arrival

deque(['Michael', 'Terry', 'Graham'])

List Comprehensions

In [242]:
squares = []
for x in range(10):
    squares.append(x**2)
    
squares

[0, 1, 4, 9, 16, 25, 36, 49, 64, 81]

In [243]:
squares = list(map(lambda x: x**2, range(10)))


In [244]:
squares = [x**2 for x in range(10)]


In [245]:
[(x, y) for x in [1,2,3] for y in [3,1,4] if x != y]

[(1, 3), (1, 4), (2, 3), (2, 1), (2, 4), (3, 1), (3, 4)]

In [246]:
combs = []
for x in [1,2,3]:
    for y in [3,1,4]:
        if x !=y:
            combs.append((x,y))
            
combs

[(1, 3), (1, 4), (2, 3), (2, 1), (2, 4), (3, 1), (3, 4)]

In [247]:
vec = [-4,-2,0,2,4]
# create a new list with the values doubled
[x*2 for x in vec]

[-8, -4, 0, 4, 8]

In [248]:
# filter the list to exclude negative numbers
[x for x in vec if x >=0]

[0, 2, 4]

In [249]:
# apply a function to all the elements
[abs(x) for x in vec]

[4, 2, 0, 2, 4]

In [251]:
#call a method on each element
freshfruit = ['banana', 'loganberry', 'passion fruit']
[weapon.strip() for weapon in freshfruit]

['banana', 'loganberry', 'passion fruit']

In [252]:
# create a list of 2-tuples like (number, square)
[(x, x**2) for x in range(6)]

[(0, 0), (1, 1), (2, 4), (3, 9), (4, 16), (5, 25)]

In [253]:
# the tuple must be parenthesized, otherwise an error is raised
[x, x**2 for x in range(6)]

SyntaxError: invalid syntax (<ipython-input-253-702d12ece8a4>, line 2)

In [254]:
# flatten a list using a listcomp with two 'for'
vec = [[1,2,3], [4,5,6], [7,8,9]]

In [255]:
[num for elem in vec for num in elem]

[1, 2, 3, 4, 5, 6, 7, 8, 9]

In [256]:
from math import pi
[str(round(pi, i)) for i in range(1, 6)]

['3.1', '3.14', '3.142', '3.1416', '3.14159']

Nested List Comprehensions

In [257]:
matrix = [
    [1,2,3,4],
    [5,6,7,8],
    [9,10,11,12]
]

In [258]:
[[row[i] for row in matrix] for i in range(4)]

[[1, 5, 9], [2, 6, 10], [3, 7, 11], [4, 8, 12]]

In [261]:
transposed = []
for i in range(4):
    #the following 3 lines implement the nested listcomp
    transposed_row = []
    for row in matrix:
        transposed_row.append(row[i])
    transposed.append(transposed_row)

transposed

[[1, 5, 9], [2, 6, 10], [3, 7, 11], [4, 8, 12]]

In [262]:
list(zip(*matrix))


[(1, 5, 9), (2, 6, 10), (3, 7, 11), (4, 8, 12)]

The del statement

In [263]:
a = [-1,1, 66.25, 333, 333, 1234.5]
del a[0]
a

[1, 66.25, 333, 333, 1234.5]

In [265]:
del a[2:4]
a

[1, 66.25]

In [266]:
del a[:]
a

[]

In [268]:
del a 
a

NameError: name 'a' is not defined

Tuples and Sequences

In [269]:
t= 12345, 54321, 'hello!'
t[0]

12345

In [270]:
t

(12345, 54321, 'hello!')

In [272]:
#Tuples may be nested:
u = t, (1,2,3,4,5)
u

((12345, 54321, 'hello!'), (1, 2, 3, 4, 5))

In [273]:
#Tuples are immutable:
t[0] = 88888

TypeError: 'tuple' object does not support item assignment

In [274]:
#but they can contain mutable objects
v= ([1,2,3], [3,2,1])
v

([1, 2, 3], [3, 2, 1])

In [275]:
empty= ()
singleton = 'hello', # <-- note trailing comma
len(empty)

0

In [276]:
len(singleton)

1

In [277]:
singleton

('hello',)

In [278]:
x, y, z = t

Sets

In [279]:
basket = {'apple', 'orange', 'apple', 'pear', 'orange', 'banana'}
print(basket)

{'apple', 'pear', 'banana', 'orange'}


In [280]:
'orange' in basket #fast membershio checking

True

In [281]:
'crabgrass' in basket

False

In [282]:
#Demonstrate set operations on unique letters from 2 words
a = set('abracadabra')
b = set('alacazam')
a # unique letters in a

{'a', 'b', 'c', 'd', 'r'}

In [283]:
a-b # letters in a but not in b

{'b', 'd', 'r'}

In [284]:
a | b    # letters in a or b or both

{'a', 'b', 'c', 'd', 'l', 'm', 'r', 'z'}

In [285]:
a & b   # letters in both a and b

{'a', 'c'}

In [286]:
a ^ b   # letters in a or b but not both

{'b', 'd', 'l', 'm', 'r', 'z'}

In [287]:
a = {x for x in 'abracadabra' if x not in 'abc'}
a

{'d', 'r'}

Dictionaries 

In [288]:
tel = {'jack': 4098, 'sape': 4139}
tel['guido'] = 4127

In [289]:
tel

{'jack': 4098, 'sape': 4139, 'guido': 4127}

In [290]:
tel['jack']

4098

In [291]:
del tel['sape']

In [293]:
tel['irv'] = 4127
tel

{'jack': 4098, 'guido': 4127, 'irv': 4127}

In [294]:
list(tel)

['jack', 'guido', 'irv']

In [295]:
sorted(tel)

['guido', 'irv', 'jack']

In [296]:
'guido' in tel

True

In [297]:
'jack' not in tel

False

In [298]:
dict([('sape', 4139), ('guido', 4127), ('jack', 4098)])

{'sape': 4139, 'guido': 4127, 'jack': 4098}

In [299]:
{x: x**2 for x in (2, 4, 6)}

{2: 4, 4: 16, 6: 36}

In [300]:
dict(sape=4139, guido=4127, jack=4098)

{'sape': 4139, 'guido': 4127, 'jack': 4098}

Looping Techniques

In [301]:
knights = {'gallahad': 'the pure', 'robin': 'the brave'}
for k, v in knights.items():
    print(k, v)

gallahad the pure
robin the brave


In [302]:
for i, v in enumerate(['tic', 'tac', 'toe']):
    print(i, v)

0 tic
1 tac
2 toe


In [303]:
questions = ['name', 'quest', 'favorite color']
answers = ['lancelot', 'the holy grail', 'blue']
for q, a in zip(questions, answers):
    print('What is your {0}?  It is {1}.'.format(q, a))

What is your name?  It is lancelot.
What is your quest?  It is the holy grail.
What is your favorite color?  It is blue.


In [304]:
for i in reversed(range(1, 10, 2)):
    print(i)

9
7
5
3
1


In [305]:
basket = ['apple', 'orange', 'apple', 'pear', 'orange', 'banana']
for f in sorted(set(basket)):
    print(f)

apple
banana
orange
pear


In [306]:
import math
raw_data = [56.2, float('NaN'), 51.7, 55.3, 52.5, float('NaN'), 47.8]
filtered_data = []
for value in raw_data:
    if not math.isnan(value):
        filtered_data.append(value)

filtered_data

[56.2, 51.7, 55.3, 52.5, 47.8]

More on conditions

In [307]:
string1, string2, string3 = '', 'Trondheim', 'Hammer Dance'
non_null = string1 or string2 or string3
non_null

'Trondheim'

CSV Loaded Example 

In [313]:
import pandas as pd

# Read data from file 'filename.csv' 
# (in the same directory that your python process is based)
# Control delimiters, rows, column names with read_csv 
data = pd.read_csv("default of credit card clients.csv", delimiter=';')

In [314]:
# Preview the first 5 lines of the loaded data 
data.head()


Unnamed: 0         X1   X2         X3        X4   X5     X6     X7     X8  \
0         ID  LIMIT_BAL  SEX  EDUCATION  MARRIAGE  AGE  PAY_0  PAY_2  PAY_3   
1          1      20000    2          2         1   24      2      2     -1   
2          2     120000    2          2         2   26     -1      2      0   
3          3      90000    2          2         2   34      0      0      0   
4          4      50000    2          2         1   37      0      0      0   

      X9  ...        X15        X16        X17       X18       X19       X20  \
0  PAY_4  ...  BILL_AMT4  BILL_AMT5  BILL_AMT6  PAY_AMT1  PAY_AMT2  PAY_AMT3   
1     -1  ...          0          0          0         0       689         0   
2      0  ...       3272       3455       3261         0      1000      1000   
3      0  ...      14331      14948      15549      1518      1500      1000   
4      0  ...      28314      28959      29547      2000      2019      1200   

        X21       X22       X23                           Y  
0  PAY_AMT4  PAY_AMT5  PAY_AMT6  default payment next month  
1         0         0         0                           1  
2      1000         0      2000                           1  
3      1000      1000      5000                           0  
4      1100      1069      1000                           0  

[5 rows x 25 columns]

Questions:

-Was it straightforward to install Python and all of the libraries? 

Yes, I already had installed python, and it was pretty straightforward.

-Was the tutorial useful? Would you recommend it to others?
In my opinion, it has an introduction focused too much in the technical side. 
Also, at the beggining of it I thought it was too basic, but as it continued a lot of complicated topics were covered very weel. 
I did not like the fact that it was not a notebook, so it took me a lot of time copy and rewrite everything, it would be easier to only have to run and understand, as many other tutorials. 
Yes, I will recommend it to others, specially for the explanations. 

-What are the main lessons you've learned from this experience?

Python has a strong community. Find resources, and troubleshooting is very easy. 
Always comment the code, it is important for your future self. 
First, try to manage the most important libraries as pandas, math and numoy. Most of the things can be donde with this. 
